# Web scraping

In [ ]:
import pandas as pd 
import numpy as np
from bs4 import BeautifulSoup
import requests
import cloudscraper

In [3]:
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
}

In [ ]:
%%sql

In [5]:
url = "https://www.yellowpages.com/los-angeles-ca/electricians"

In [4]:
scraper = cloudscraper.create_scraper()  # This handles the Cloudflare challenge

In [5]:
response = scraper.get(url)
response

In [6]:
soup = BeautifulSoup(response.text, 'html.parser')

In [7]:

company = soup.find_all('div', class_='result')

In [8]:
length = len(company)
length

36

In [9]:
name=[]
phone_number=[]
address=[]

for i in company:
    n = i.select_one('a.business-name span')
    p = i.find('div', class_='phones phone primary')
    a = i.select_one('div.adr, div.street-address, div.locality')

    name.append(n.text.strip() if n else None)
    phone_number.append(p.text.strip() if p else None)
    address.append(a.text.strip() if a else None)
 

df=pd.DataFrame({'Name':name,
   'Phone Number':phone_number,
   'Address':address,
   })

In [10]:
df

,Name,Phone Number,Address
0,None,None,None
1,None,None,None
2,None,None,None
3,None,None,None
4,None,None,None
5,None,None,None
6,Fondas Electric Inc,(213) 261-9752,"310 N Hoover StLos Angeles, CA 90004"
7,Juan de Jesus Inc. General Contractors,(310) 720-6833,"5300 11th AveLos Angeles, CA 90043"
8,Suncoast Energy,(562) 999-1964,None
9,USA Electrical REPAIRS Services,(818) 861-6643,"La Crescenta-Montrose, CA 91214"
10,Express Electrical Services,(888) 719-5178,None
11,Quality Electrical Services,(888) 645-6806,"Burbank, CA 91502"
12,"All Pro Plumbing, Heating, Air & Electrical",(909) 253-0664,"5001 Ontario Mills PkwyOntario, CA 91764"
13,Express Electrical Services,(213) 626-4277,"1011 Goodrich BlvdCommerce, CA 90022"
14,Express Electrical Service - Los Angeles,(213) 626-4277,"1011 Goodrich BlvdCommerce, CA 90022"
15,Halsted & Hoggan Inc,(213) 652-4748,"935 S Santa Fe AveLos Angeles, CA 90021"
16,Hye Electric & Son,(323) 231-0011,None
17,Gibbs Brothers Electric Co Inc,(800) 471-1126,"1703 N Main StLos Angeles, CA 90012"
18,Jose Cruz Plumbing Heating & Electrical,(323) 222-1804,"4334 Huntington Dr SLos Angeles, CA 90032"
19,Daylight Electric,(323) 655-5252,"5951 W 3rd StLos Angeles, CA 90036"
20,Southwest Industrial Electric,(323) 215-1273,"4557 York BlvdLos Angeles, CA 90041"
21,Luminous Electric,(310) 339-2473,"8506 Lilienthal AveLos Angeles, CA 90045"
22,Mtz Electric,(213) 387-6791,"909 S Ardmore Ave Apt 1Los Angeles, CA 90006"
23,Durousseau Electric,(323) 734-2424,"2526 W Jefferson BlvdLos Angeles, CA 90018"
24,Jerrys All Phase Electric,(323) 294-0684,"6302 S Rimpau BlvdLos Angeles, CA 90043"
25,Branover Contractors Inc,(323) 467-6661,"Los Angeles, CA 90068"
26,Buffalo Electric Wholesale,(213) 765-5100,"1220 Venice BlvdLos Angeles, CA 90006"
27,JGJ Electrical Services,(310) 480-7767,"12903 Belhaven AveLos Angeles, CA 90059"
28,Supreme Electric Inc,(323) 753-5131,"438 E 71st StLos Angeles, CA 90003"
29,Mr. Electric,(323) 465-4448,"918 N Western AveLos Angeles, CA 90029"
30,Patino Electric,(310) 901-8657,"4001 W 21st StLos Angeles, CA 90018"
31,Wells Electric LA,(562) 821-3107,"518 S Laverne St.Los Angeles, CA 90022"
32,Bright Electric La,(562) 359-8532,"749 Fraser AveLos Angeles, CA 90022"
33,American Electrician,(310) 553-5157,"8391 Beverly BlvdLos Angeles, CA 90048"
34,Brentwood Electrical Experts,(310) 666-4752,"11950 San Vicente BlvdLos Angeles, CA 90049"
35,Islas Electric and Handyman Services,(310) 621-2682,"Los Angeles, CA 90047"

In [12]:
df

Empty DataFrame
Columns: [Name, Phone Number, Address]
Index: []

In [257]:
df

,Name,Phone Number,Address
0,Fondas Electric Inc,(213) 261-9752,"310 N Hoover StLos Angeles, CA 90004"
1,Juan de Jesus Inc. General Contractors,(310) 720-6833,"5300 11th AveLos Angeles, CA 90043"
2,USA Electrical REPAIRS Services,(818) 861-6643,"La Crescenta-Montrose, CA 91214"
3,Quality Electrical Services,(888) 645-6806,"Burbank, CA 91502"
4,"All Pro Plumbing, Heating, Air & Electrical",(909) 253-0664,"5001 Ontario Mills PkwyOntario, CA 91764"
...,...,...,...
545,Electrical Master,(213) 392-3908,"606 N Figueroa StLos Angeles, CA 90012"
546,HMT Electric,(213) 265-7675,"900 S Figueroa StLos Angeles, CA 90015"
547,Schematic Industrial Electric LLC,(323) 244-2666,"929 S Figueroa StLos Angeles, CA 90015"
548,Electric Contractors Company,(213) 477-7043,"900 W Olympic BlvdLos Angeles, CA 90015"
549,Er Haskins Electric Service,(818) 247-8997,"407 E Pico Blvd Ste 308Los Angeles, CA 90015"

In [231]:
df = df.dropna(ignore_index=True)

In [256]:
df['Name'].nunique(), df['Phone Number'].nunique(), df['Address'].nunique()

(154, 144, 153)

In [ ]:
final=pd.DataFrame()
for j in range(1,1001):
  webpage=requests.get('https://www.ambitionbox.com/list-of-companies?page={}'.format(j)).text
  soup=BeautifulSoup(webpage,'lxml')
  company=soup.find_all('div',class_='company-content-wrapper')
  name=[]
  rating=[]
  reviews=[]
  ctype=[]
  hq=[]
  how_old=[]
  no_of_employee=[]

  for i in company:

    try:
       name.append(i.find('h2').text.strip())
    except:
       name.append(np.nan)

    try:
       rating.append(i.find('p',class_='rating').text.strip())
    except:
       rating.append(np.nan)
   
    try:

      reviews.append(i.find('a' , class_='review-count').text.strip())
    except:
      reviews.append(np.nan)

    try:

      ctype.append(i.find_all('p',class_='infoEntity')[0].text.strip())
    except:
      ctype.append(np.nan)
    try:

      hq.append(i.find_all('p',class_='infoEntity')[1].text.strip())
    except:
      hq.append(np.nan)
    
    try:

      how_old.append(i.find_all('p',class_='infoEntity')[2].text.strip())
    except:
      how_old.append(np.nan)
    try:
      no_of_employee.append(i.find_all('p',class_='infoEntity')[3].text.strip())
    except:
      no_of_employee.append(np.nan)
    

  df=pd.DataFrame({'name':name,
    'rating':rating,
    'reviews':reviews,
    'company_type':ctype,
    'Head_Quarters':hq,
    'Company_Age':how_old,
    'No_of_Employee':no_of_employee,
    })
  
  final=final.append(df,ignore_index=True)